### ISSUE TITLE
Rename the default gateway environment "Production and Sandbox" to "Default"

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-apim#10477]
### Describe your problem(s)
Current default config:

```toml
[[apim.gateway.environment]]
name = "Production and Sandbox"

```
Expected Config:
```toml
[[apim.gateway.environment]]
name = "Default"

```

### How will you implement it

---
