### ISSUE TITLE
Show HTTPS port when try out with HTTP in Dev Portal

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-apim#10869]
### Description:
The environments is configured with following
```toml
http_endpoint = "http://gw.apim.com:8290"
https_endpoint = "https://gw.apim.com:8253"
```

shows HTTPS port when select HTTP in try out page

![image](https://user-images.githubusercontent.com/23183042/113981152-f46f0480-9864-11eb-868c-ea99b72d6fa2.png)
