### ISSUE TITLE
[3.2.0] Custom Keystore TOML Configurations are not working

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#10915]
### Description:

The TOML configurations and the J2 Mapping to create custom Keystores in the `carbon.xml` are not working properly. The presented J2 templates in the `carbon.xml.j2` are inoperative. Following is the default J2 template to configure a custom keystore in the API Manager server

```j2
{% for key,keyStore in custom_keystore.items() %}
        <{{key}}>
            <!-- Keystore file location-->
            <Location>${carbon.home}/repository/resources/security/{{keyStore.file_name}}</Location>
            <!-- Keystore type (JKS/PKCS12 etc.)-->
            <Type>{{keyStore.type}}</Type>
            <!-- Keystore password-->
            <Password>{{keyStore.password}}</Password>
            <!-- Private Key alias-->
            <KeyAlias>{{keyStore.alias}}</KeyAlias>
            <!-- Private Key password-->
            <KeyPassword>{{keyStore.key_password}}</KeyPassword>
        </{{key}}>
{% endfor %}
```

### Steps to reproduce:

- Configure a custom Keystore in API Manager v3.2.0 using the following TOML configurations and verify the populated configurations in the `carbon.xml` artifact (once the server is started)

  ```toml
  [custom_keystore]
  APIKeyKeyStore = "APIKeyKeyStore"

  [APIKeyKeyStore]
  file_name =  "newkeystore.jks"
  type =  "JKS"
  password =  "mypassword"
  alias =  "custom_api_key_alias"
  key_password =  "mypassword"
  ```

### Affected Product Version:

- API Manager v3.2.0

**Comment by athiththan11** [comment]
Made few enhancements to the J2 template related to configuring custom Keystore in `carbon.xml.j2`. Given below is the updated J2 template

```j2
{% for keyStore in custom_keystore %}
        <{{keyStore.key}}>
            <!-- Keystore file location-->
            <Location>${carbon.home}/repository/resources/security/{{keyStore.file_name}}</Location>
            <!-- Keystore type (JKS/PKCS12 etc.)-->
            <Type>{{keyStore.type}}</Type>
            <!-- Keystore password-->
            <Password>{{keyStore.password}}</Password>
            <!-- Private Key alias-->
            <KeyAlias>{{keyStore.alias}}</KeyAlias>
            <!-- Private Key password-->
            <KeyPassword>{{keyStore.key_password}}</KeyPassword>
        </{{keyStore.key}}>
{% endfor %}
```

And the respective TOML configuration to define a custom Keystore

```toml
[[custom_keystore]]
key = "APIKeyKeyStore"
file_name =  "newkeystore.jks"
type =  "JKS"
password =  "mypassword"
alias =  "custom_api_key_alias"
key_password =  "mypassword"
```

**Comment by athiththan11** [comment]
Closing this as we can use the following TOML configurations for the custom Keystore

```toml
[custom_keystore.APIKeyKeyStore]
file_name =  "newkeystore.jks"
type =  "JKS"
password =  "mypassword"
alias =  "custom_api_key_alias"
key_password =  "mypassword"
```
