### ISSUE TITLE
Finalize the operation policy specification

### ISSUE THREAD

**Issue by 1akshitha** [wso2/product-apim#12268]
### Describe your problem(s)
Finalize the operation policy specification that can cover all the operation policy usecases and document the spec.

**Comment by ashera96** [comment]
Finalized operation policy specification of `Add Header` policy is attached herewith for easy reference:

``` yaml
category: Mediation
name: addHeader
displayName: Add Header
description: With this policy, user can add a new header to the request
applicableFlows : ["request","response","fault"]
supportedGateways: ["Synapse", "ChoreoConnect"]	
supportedApiTypes : ["HTTP"]
multipleAllowed: true
attributes:
 -
  name: headerName
  displayName: Header Name
  description : Name of the header to be added
  validationRegex: ^([a-zA-Z_][a-zA-Z\\d_\\-\\ ]*)$
  type : String
  required: true
  defaultValue: null
  allowedValues: []
 -
  name: headerValue
  displayName : Header Value
  description : Value of the header
  validationRegex : ^([a-zA-Z\\d_][a-zA-Z\\d_\\-\\ ]*)$
  type : String
  required : true
  defaultValue: null
  allowedValues: []
```
