### ISSUE TITLE
[C5][environment][api-overview] Multi-Environment API Overview

### ISSUE THREAD

**Issue by RenukaFernando** [wso2/product-apim#2299]
**Description:**
Let's assume three environments with an API, "weather API".

![api_diff](https://user-images.githubusercontent.com/23183042/34708786-631db2a4-f53a-11e7-9bbf-9ca9601a25b9.png)
Figure 01: Multi-Environment API Overview for Weather API

- The user has to login to an environment and clicks on a button in the API overview page to get the `Multi-Environment API Overview` of the API.
- The UI Service make requests to all environments to get API details.
- `JWT Grant Type` is used to get access token from environments.

API version, lifecycle state is shown in the overview page.

**Affected Product Version:**
- API Manager 3.0.0 

**Related Issues:**
https://github.com/wso2/product-apim/issues/2629: Multi-Environment Authentication

**Comment by lakwarus** [comment]
The main functionality is to have an overview on how APIs are deployed across deterrent environment.  This is something like API governance view.  Within single UI, user can see how an API deployed across multi environment.

**Comment by tmkasun** [comment]
@RenukaFernando it seems this feature will be available for those who configure the API Manager multi-environment support, If so don't they(users) needs to login to each environment where they want to compare an API ?

**Comment by lakwarus** [comment]
@tmkasun Yes, technically they want to login. But asking to login to each and every environment is not very nice. We can have multiple options here.
# option1 :  is getting admin credentials as a config and do admin call to retrieve API details.  
# option2 : using JWT grant, getting access token for each environment and retrieve API details by using relevant access token

IMO option #2 is better from user's point of view. To work this we need to have JWT grand type support in Key Manager.

**Comment by harsha89** [comment]
Hi Renuka,

So this feature will be added to the publisher only right? How will a user be the benefit of having this feature? Since he simply can switch the environment and check the API status. I think we would need to add few extra things that user is interested in an API across the environment.

Thanks,
Harsha

**Comment by RenukaFernando** [comment]
Sample UI for the required feature.
![api_overview](https://user-images.githubusercontent.com/23183042/34761882-a2ceebf8-f60b-11e7-9f53-6c2e0fc4ea77.png)

**Comment by Minoli** [comment]
Hi Renuka,
Please see the below image for some UI level suggestions. 
![multi_env_overview1](https://user-images.githubusercontent.com/9837443/34869480-0aa5ef54-f7ad-11e7-84c1-07d58298d667.png)
User can select the lifecycle state from dropdown for each envirnment.

**Comment by RenukaFernando** [comment]
The user should be authenticated to all environments to retrieve API details. The authentication process is going to be done using JWT grant type.

## Authentication Process
Sample scenario: Two environments (Dev and Prod)
- The user login to an environment (Development environment) using Password or Authorization Code grant type (1 to 8).
- The client web application receives both Access Token and JWT.
- Access Token is set as cookies.
- JWT is passed to authenticate other environments (Production environment) and then `JWT is discarded` (A to H).
- The client web application receives an Access Token and it is set as cookies.
![design](https://user-images.githubusercontent.com/23183042/35323688-69d3e90c-0114-11e8-8569-54957d6f2183.png)

**Comment by RenukaFernando** [comment]
The feature is disabled by default and the below configuration is going to be used to enable the feature. If JWT grant type is not supported by the IDP, the user can use a similar grant as an extension point.

### The configuration with default values is as follows.
```yaml
  # APIM Configuration Parameters
wso2.carbon.apimgt:
    # Environment Configurations
  environmentConfigurations:
      # Multi-Environment Overview Configurations
    environmentOverviewConfigs:
        # Multi-Environment Overview feature enabled or not
      enabled: false
        # Authentication Grant Type to authenticate user to other environments
      authenticationGrantType: "urn:ietf:params:oauth:grant-type:jwt-bearer"
```
