### ISSUE TITLE
[APIM 3.0.0]Can't change(override) access token validity period

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#3633]
**Description:**
I have changed the `defaultTokenValidityPeriod` [configuration value](https://github.com/wso2/product-apim/blob/master/modules/distribution/carbon-home/conf/deployment.yaml#L455) in **<APIM3_HOME>/conf/default/deployment.yaml** file as below
```yaml
wso2.carbon.auth:
    # Key Management Configurations
  keyManagerConfigs:
      # Access token default validity period
    defaultTokenValidityPeriod: 1989
```

But it din't get reflected in `accessTokenInfo` object in [here](https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/main/java/org/wso2/carbon/apimgt/rest/api/authenticator/AuthenticatorAPI.java?utf8=%E2%9C%93#L109)

**Affected Product Version:**
- APIM 3 m28

**OS, DB, other environment details and versions:**    
- H2
