### ISSUE TITLE
Importing an OAS3 Definition does not populate API context in the UI

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#4471]
**Description:**
Currently, $subject is not supported. Check about the possibility of doing it.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by malinthaprasan** [comment]
There are several things which make it hard to achieve:

1. We have no way to specify a specific basePath value in OAS3 definition. In OAS2, we can define the basePath field and that is pretty much straightforward to fill the context field using that.

2. In OAS3, what we have is "servers" object instead. That is also not mandatory [1]. REQUIRED is not defined in the "servers" field in the specification. Therefore, if that is not present in an imported OAS3 definition, we cannot fill the context field in Publisher anyway. Here this example [2] does not have "servers" defined.

3. OAS2 supports only one (and mandatory) basePath field. But in OAS3, it can have multiple server URLs. It is difficult to decide which server URL should be choosen to fill the context in Publisher. Please see the examples in [3] where multiple server URLs can be defined.
```
servers:
  - url: https://api.example.com/v1
    description: Production server (uses live data)
  - url: https://sandbox-api.example.com:8443/v1
    description: Sandbox server (uses test data)
```
4. Even if a server URL is selected, there's no defined way to extract the basePath from a server URL.

[1] https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schema
[2] Example without "servers": https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/api-with-examples.yaml
[3] Example with multiple "servers": https://swagger.io/docs/specification/api-host-and-base-path/
