### ISSUE TITLE
[Publisher] Swagger Parser does not support default value for arryas

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#4691]
**Description:**
Issue when uploading a swagger definition when creating an API on publisher UI. 
The error:
`swagger.yaml contains an invalid swagger definition.  attribute paths.'/beneficiaries/create'(post).[payment_types[]].default is not of type `string` 
`
**Sample**
```
parameters:
  - name: 'payment_types[]'
    in: formData
    required: false
    type: array
    items:
      type: string
      enum:
        - priority
        - regular
    default:
      - priority
    description: payment type

```
The issue is fixed in latest swagger-parser version 1.0.41. In APIM, the swagger parser dependency which is available in the runtime is the swagger parser which comes with swagger-codegen, which we ship with the product. We are using the swagger.parser version v1.0.32 with swagger codegen 2.2.3. To fix the issue, we need to swagger-codegen upgrade to 2.4.1. 

**Suggested Labels:**
APIM, 2.6, committement

**Affected Product Version:**
APIM 2.6

**OS, DB, other environment details and versions:**   
- 

**Steps to reproduce:**
Import the sample swagger in Publisher

**Related Issues:**
https://github.com/swagger-api/swagger-parser/issues/387
https://github.com/swagger-api/swagger-parser/pull/886
