### ISSUE TITLE
[3.0.0] Setting synapse transport sender parameters not work.

### ISSUE THREAD

**Issue by menakaj** [wso2/product-apim#6731]
Requirement:
- Set different values to PassthroughHTTPSSLSender configuration in axis2.xml

Approach.
- Add configuration to <API-M_HOME>/repository/conf/deployment.toml file.

```toml
    [transport.passthru_https.sender.parameters]
    HostnameVerifier = "AllowAll"
```

The configured value is not reflected in the axis2.xml file after starting the server.
