### ISSUE TITLE
API Manager analytics 3.1.0-M3 doesn't support oracle due to time format different

### ISSUE THREAD

**Issue by ruks** [wso2/product-apim#7028]
Analytics widgets based on AM DB doesn't work due to the time format different in the Database. But the time format can be changed at the connection initialization time and it does not affect the database actual persistent format.
This can be done by adding a connection initial query.

`alter session set NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS'`

The following data sources need to be applied in the dashboard runtime.
ex:
``` yaml
  - name: AM_DB
    description: Main datasource used by API Manager
    jndiConfig:
      name: jdbc/AM_DB
    definition:
      type: RDBMS
      configuration:
        jdbcUrl: "jdbc:oracle:thin:@localhost:1521:XE"
        username: amdb
        password: amdb
        driverClassName: oracle.jdbc.OracleDriver
        maxPoolSize: 10
        idleTimeout: 60000
        connectionTestQuery: SELECT 1
        connectionInitSql: alter session set NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS'
        validationTimeout: 30000
        isAutoCommit: false
```
