### ISSUE TITLE
SOAP to REST conversion some of the XMLSchema built-in data types were also converted wrongly to objects instead of the relevant Swagger data types

### ISSUE THREAD

**Issue by Seralahthan** [wso2/product-apim#7078]
Hi, 

When we try to create REST API by referencing a WSDL file/URL some of the data types are not getting converted properly in the swagger definition. Due to this when we try to build the SDK created for this API there are errors with missing classes.

The following 3 **XMLSchema built-in data types** were also converted wrongly to **objects** instead of the relevant **Swagger data types**.
```
integer: 
      type: object
      xml:
        namespace: "http://www.w3.org/2001/XMLSchema"
        prefix: xs

string: 
      type: object
      xml:
        namespace: "http://www.w3.org/2001/XMLSchema"
        prefix: xs

decimal: 
      type: object
      xml:
        namespace: "http://www.w3.org/2001/XMLSchema"
        prefix: xs
```

Due to this, a **String class** is created in the **org.wso2.client.model.<API_Name>** package in the generated SDK which conflicts with the default **String class** in **java.lang.String** package.

**Comment by malinthaprasan** [comment]
Tagging https://github.com/wso2/product-apim/issues/7108

**Comment by vithu30** [comment]
I have tried the scenario in latest WUM pack of 2.6.0 and latest built pack of 3.1.0 and unable to reproduce the issue. When generating swagger definition from the provided WSDL, the above mentioned data types are correctly assigned in swagger. An example definition:
```
getUserList:
    type: object
    properties:
      claimUri:
        type: string
      claimValue:
        type: string
      profile:
        type: string
    xml:
      namespace: "http://www.w3.org/2001/XMLSchema"
      prefix: xs
    x-namespace-qualified: true
```

Can you let us know the exact steps to reproduce the issue and the API Manager version you tried. Also, it would be great if you can attach the WSDL file you have used.
