### ISSUE TITLE
Importing an API in CTL can result in APIs with names with spaces 

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#7641]
### Description:
Importing below API with ctl will result in API with the name "Swagger Petstore". We do not allow APIs with spaces in the name.

```
id:
  providerName: admin
  apiName: Swagger Petstore
  version: 1.0.3
description: 'This is a sample server Petstore server.  You can find out more about
  Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For
  this sample, you can use the api key `special-key` to test the authorization filters.'
type: HTTP
context: /v2/1.0.3
contextTemplate: /v2/{version}
tags:
- pet
- store
- user
availableTiers:
- name: Unlimited
status: CREATED
visibility: public
transports: http,https
productionUrl: http://petstore.swagger.io/v2
sandboxUrl: http://petstore.swagger.io/v2
```
