### ISSUE TITLE
APIM does not honour the context template provided

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-apim#7739]
### Description:
Create an apictl project as attached
[oauth2.zip](https://github.com/wso2/product-apim/files/4337260/oauth2.zip)

It has following met information in api.yaml file

```yaml
id:
  providerName: admin
  apiName: Petstore
  version: 1.0.0
type: HTTP
context: /petstore/v1
contextTemplate: /petstore/v1
```

The import the project to the APIM. Then publish the api from lifecycle tab without any other change. Then API will be expose with the context **/petstore/v1**, which is correct

Then do some modification to API and re publish it. Then API will be exposed with **/petstore/v1/1.0.0**.
Seems like APIM is appending the version to the context irrespective of the context template.

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by malinthaprasan** [comment]
@Rajith90 shouldn't we specify where the version is in the context template?
And, if the version of the API is v1, any particular reason the version is mentioned as 1.0.0?

IMO, the correct one should be: 
```
id:
  providerName: admin
  apiName: Petstore
  version: v1
type: HTTP
context: /petstore/v1
contextTemplate: /petstore/{version}
```

Can we check the above one?
