### ISSUE TITLE
axis.xml.j2 files not reflect transport.jms.sender properties

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-apim#8109]
### Description:
axis.xml.j2 files not reflect transport.jms.sender properties.

#### sample deployment toml
```toml
[transport.jms]
sender_enable = true
[[transport.jms.sender]]
name = "Sample"
parameter.'java.naming.provider.url' = "..."
...
```

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---
