### ISSUE TITLE
IS as KM: Kerberos Grant enabling documentation error

### ISSUE THREAD

**Issue by chathuranga95** [wso2/product-apim#8894]
### Description:
When configuring Kerberos Grant using IS as KM, step 4 under [this section](https://apim.docs.wso2.com/en/next/learn/api-security/oauth2/grant-types/kerberos-oauth2-grant/#configuring-kerberos-grant-using-is-as-km) is faulty.

deployment.toml file entry should be corrected as:

```toml
[oauth.grant_type.kerberos]
enable = true
```
