### ISSUE TITLE
x-wso2-application-security is not supported when defined in API definition

### ISSUE THREAD

**Issue by Chamindu36** [wso2/product-apim#9133]
### Describe your problem(s)
x-wso2-application-security is not supported when defined in API definition when creating an API with existing API definition.
This application security values should be applied under the runtime configurations in API. 

When the Following extension is defined in the API definition this should reflect it's changed configs in publisher UI which is not supported currently.
```
 x-wso2-application-security: 
        security-types: 
          - "api_key"
        optional: false
```

### Describe your solution
Provide extension support at the parser level.

### Related Issues
https://github.com/wso2/product-apim-tooling/issues/469
