### ISSUE TITLE
[APIM-2.6.0] Root path being removed from the Swagger definition

### ISSUE THREAD

**Issue by lkokila** [wso2/product-apim#9674]
### Description:
APIs created with Swagger definitions containing a resource with the root path ("/") as follows, drop the ("/") character from the path (checked through the publisher's swagger editor). When these resources are invoked there are runtime errors in the Gateway.  

```
  "/":
    put:
      tags:
        - CustomerResponse
      summary: CustomDescription
```

![image](https://user-images.githubusercontent.com/5971789/103412332-a29a4c80-4b9a-11eb-8bf1-6de9b0d2241d.png)

This is generated through the updates done in https://github.com/wso2-support/carbon-apimgt/pull/2514

### Affected Product Version:
APIM-2.6.0 (WUM - 1608825656158)
