### ISSUE TITLE
[3.2.0] J2 Templates are missing for Registry Handlers

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#9932]
### Description:

APIM 3.2.0 is missing J2 configuration templates in `registry.xml.j2` to integrate Registry Handlers and to configure them via  `deployment.toml`

### Affected Product Version:

- APIM 3.2.0

**Comment by athiththan11** [comment]
Hi Team

We can introduce a template as following to fulfill the requirement.

```j2
{% for handler in registry_handler %}
<handler class="{{handler.class}}" {% if handler.method is defined %} method="{{handler.method}}" {% endif %}>
    {% for propKey,propValue in handler.properties.items() %}
    <property name="{{propKey}}">{{propValue}}</property>
    {% endfor %}
    {% if handler.nested_property.enable %}
    <property name="{{handler.nested_property.name}}" type="{{handler.nested_property.type}}">
        {% for prop in nested_properties[handler.nested_property.name] %}
            <{{prop.tag}} {% if prop.key is defined %} key="{{prop.key}}" {% endif %}>{{prop.value}}</{{prop.tag}}>
        {% endfor %}
    </property>
    {% endif %}
    <filter class="{{handler.filter_class}}">
        {% for filterPropKey,filterPropValue in handler.filter_properties.items() %}
        <property name="{{filterPropKey}}">{{filterPropValue}}</property>
        {% endfor %}
    </filter>
</handler>
{% endfor %}
```

The corresponding `TOML` configurations will be as following

```toml
# define a registry handler
[[registry_handler]]
class = "RegistryHandlerClass"
method = "PUT,GET"
filter_class = "RegistryFilterClass"

# define registry handler property elements
[registry_handler.properties]
propertyOne = "propertyOneVlaue"

# define registry handler filter elements
[registry_handler.filter_properties]
filterProperty = "filterPropertyValue"

# define custom property elements
[registry_handler.nested_property]
enable = true
name = "RegistryNestedPropertyName"
type = "xml"

# the key should be as nested_properies.'<name defined for nested_property>'
[[nested_properties.RegistryNestedPropertyName]]
tag = 'Tag'
key = 'key'
value = 'value'
[[nested_properties.RegistryNestedPropertyName]]
tag = 'Tag'
key = 'AnotherKey'
value = 'Anothervalue'
```
